---
title: "HW8_MandMs"
---

In this assignment, you'll be picking up where you left off with the M&Ms activity. You'll load the data and perform some basic statistical analysis. Follow the steps below to complete the assignment.

### Task 1: Load the tidyverse


### Task 2: Load the M&Ms dataset from https://raw.githubusercontent.com/dwillis/jour405/refs/heads/main/data/mandms.csv


### Task 3: Sample 5 rows of data from the dataset


### Task 4: Calculate the mean age and standard deviation of the sample, using either the blue or white number of M&Ms


### Task 5: Calculate the mean age and standard deviation of the population, using the same measure as in Task 4


### Task 6: Compare the sample and population statistics

Compare the two sets of means and standard deviations. Are they similar?

### Task 7: Describe the results

Write a few sentences about what you found in the data. What does this tell you about the M&Ms dataset and about the act of random sampling?


When finished, save your work, switch to GitHub Desktop, then add, commit and push your changes to GitHub and submit the URL of the notebook in ELMS.
